---
deployment:
  tasks:
    - export REPOPATH=/home/h36888c/repositories/schoollunch/*
    - export SITEPATH=/home/h36888c/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
